//
// Created by lalit on 6/11/2026.
//

#ifndef BOUNCINGPLUS_FIREBASE_KEYS_H
#define BOUNCINGPLUS_FIREBASE_KEYS_H

#define FIREBASE_API_KEY    "@FIREBASE_API_KEY@"
#define FIREBASE_APP_ID     "@FIREBASE_APP_ID@"
#define FIREBASE_PROJECT_ID "@FIREBASE_PROJECT_ID@"

#endif //BOUNCINGPLUS_FIREBASE_KEYS_H